### ISSUE TITLE
perlito5.js throws an error with the "Hello World" program.

### ISSUE THREAD

**Issue by shlomif** [fglock/Perlito#18]
When I run node perlito5.js on Mageia Linux Cauldron (with perl-5.18.1-3.mga4 and nodejs-0.10.22-1.mga4 ) I get:

```text
shlomif@telaviv1:~/Download/unpack/perl/Perlito/Perlito$ node perlito5.js -I./src5/lib -e 'print "Hi!\n"'
Warning: RangeError: Maximum call stack size exceeded
undefined
Error
    at CORE.warn (/home/shlomif/Download/unpack/perl/Perlito/Perlito/perlito5.js:1142:24)
    at p5pkg.main.Hash_INC (/home/shlomif/Download/unpack/perl/Perlito/Perlito/perlito5.js:18128:23)
    at /home/shlomif/Download/unpack/perl/Perlito/Perlito/perlito5.js:18130:8
    at Object.<anonymous> (/home/shlomif/Download/unpack/perl/Perlito/Perlito/perlito5.js:18279:3)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
```

"make test" is also failing all tests.

Please look into fixing it.

Regards,

-- Shlomi Fish

**Comment by fglock** [comment]
maybe related:
http://stackoverflow.com/questions/20936486/node-js-maximum-call-stack-size-exceeded
http://stackoverflow.com/questions/7663957/debugging-maximum-call-stack-size-exceeded

the error seems to happen only with some combinations of OS and nodejs version.

I'll reopen the bug if I get more information.
