### ISSUE TITLE
«TypeError: Cannot call method 'require' of undefined» after compiling expand-solitaire-multi-card-moves

### ISSUE THREAD

**Issue by shlomif** [fglock/Perlito#23]
After I compile perlito and run it on the code here - https://github.com/shlomif/fc-solve/tree/Games-Solitaire-Verify--for-Perlito--Get-Rid-of-Getopt-Long , I'm getting an error:

``` text
shlomif@telaviv1:~/Download/unpack/perl/Perlito/Perlito$ perl perlito5.pl -Cjs -I src5/lib/ -I/home/shlomif/progs/freecell/git/fc-solve/cpan/Games-Solitaire-Verify/Games-Solitaire-Verify/lib /home/shlomif/progs/freecell/git/fc-solve/cpan/Games-Solitaire-Verify/Games-Solitaire-Verify/script/expand-solitaire-multi-card-moves > ~/e.js
shlomif@telaviv1:~/Download/unpack/perl/Perlito/Perlito$ node ~/e.js
/home/shlomif/e.js:2330
                p5pkg["Perlito5::Grammar::Use"]["require"]([p5str('Games::Solitaire::Verify:
                                                          ^
TypeError: Cannot call method 'require' of undefined
    at p5pkg.Fcntl.List_ISA (/home/shlomif/e.js:2330:45)
    at /home/shlomif/e.js:2389:4
    at Object.<anonymous> (/home/shlomif/e.js:8435:3)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3
```

Please look into fixing it.

Regards, -- @shlomif

**Comment by fglock** [comment]
update on this: module pre-compilation is in the TODO list;

this is a low priority task because replacing "require" with "use" will precompile.
