### ISSUE TITLE
«Error: Died: method not found: seq_build_by in class Games::Solitaire::Verify::VariantParams» after building expand-solitaire-multi-card-moves

### ISSUE THREAD

**Issue by shlomif** [fglock/Perlito#27]
Running this script:

``` bash
#!/bin/bash

git_repo="$HOME/progs/freecell/git"
gsv="$git_repo/fc-solve/cpan/Games-Solitaire-Verify"

inc()
{
    local path="$1"
    shift
    echo "-I" "$gsv/$path/lib"
}

BASE="MyDir"
BASE_LIB="MyDir/lib"

for bn in "Games-Solitaire-Verify" "POSIX--replacement" "Exception-Class--replacement" "Getopt-Long--replacement" "List-Util--replacement" "Class-XSAccessor--replacement" ; do
    p="$gsv/$bn/lib"
    find "$p" -name '*.pm' | (while read fn ; do
        g="${fn##$p/}"
        mkdir -p "$BASE_LIB/$(dirname "$g")"
        perl -lp -MSQ -e 's#\Ause parent $sq([^$sq]+)$sq;#use $1 (); use vars qw(\@ISA); \@ISA = (qw($1));#' < "$fn" > "$BASE_LIB/$g"
    done)
done

# perl -MCarp::Always perlito5.pl -Cjs -I src5/lib/ $(inc "Games-Solitaire-Verify") $(inc "POSIX--replacement") $(inc "Exception-Class--replacement") $(inc "Getopt-Long--replacement") $(inc "List-Util--replacement") $(inc "Class-XSAccessor--replacement")  "$gsv"/Games-Solitaire-Verify/script/expand-solitaire-multi-card-moves
perl -MCarp::Always perlito5.pl -Cjs -I src5/lib/ -I "$BASE_LIB" "$gsv"/Games-Solitaire-Verify/script/expand-solitaire-multi-card-moves
```

gives me this:

```
shlomif@telaviv1:~$ node ~/expand-solitaire-multi-card-moves.js 

/home/shlomif/expand-solitaire-multi-card-moves.js:931
                throw(err)
                      ^
Error: Died: method not found: seq_build_by in class Games::Solitaire::Verify::VariantParams
Error
    at CORE.die (/home/shlomif/expand-solitaire-multi-card-moves.js:1907:24)
    at p5call (/home/shlomif/expand-solitaire-multi-card-moves.js:181:20)
    at /home/shlomif/expand-solitaire-multi-card-moves.js:3780:8
    at p5for_lex (/home/shlomif/expand-solitaire-multi-card-moves.js:922:13)
    at tmp179 [as _init] (/home/shlomif/expand-solitaire-multi-card-moves.js:3774:5)
    at p5call (/home/shlomif/expand-solitaire-multi-card-moves.js:156:44)
    at tmp106 (/home/shlomif/expand-solitaire-multi-card-moves.js:2248:5)
    at p5call (/home/shlomif/expand-solitaire-multi-card-moves.js:160:20)
    at p5pkg.POSIX.List_ISA (/home/shlomif/expand-solitaire-multi-card-moves.js:3881:60)
    at /home/shlomif/expand-solitaire-multi-card-moves.js:3926:4
```

Seems like the method is not constructed in run time.

**Comment by fglock** [comment]
update: BEGIN blocks are now working

**Comment by fglock** [comment]
Some of the problems are now fixed - in particular, BEGIN blocks now work in JavaScript and Java, and some of the core modules now work.

Some problems can't be easily fixed - for example, only some functions of POSIX.pm can be ported.

Possible follow up tasks: rewrite some of the problems we found here into unit tests.
