### ISSUE TITLE
perldoc -f open (and possibly some other related filehandle functions?) is not implemented yet

### ISSUE THREAD

**Issue by shlomif** [fglock/Perlito#29]
perldoc -f open (and possibly some other related filehandle functions?) is not implemented yet. If I do using the fc-solve git master this:

```
shlomif@telaviv1:~/Download/unpack/perl/Perlito/Perlito$ bash /home/shlomif/progs/freecell/git/fc-solve/cpan/Games-Solitaire-Verify/pack-for-perlito.bash > ~/e.js
shlomif@telaviv1:~/Download/unpack/perl/Perlito/Perlito$ pi-make-microsoft-freecell-board -t 24 | fc-solve -p -t -sam -sel > ~/24.sol
shlomif@telaviv1:~/Download/unpack/perl/Perlito/Perlito$ node ~/e.js ~/24.sol

/home/shlomif/e.js:7145
                                                p5or(p5pkg["Games::Solitaire::Verify::App::CmdLine::Expand"].open([v_fh,
                                                                                                             ^
TypeError: Object [object Object] has no method 'open'
    at tmp499 [as run] (/home/shlomif/e.js:7145:68)
    at p5call (/home/shlomif/e.js:156:44)
    at /home/shlomif/e.js:7172:2
    at Object.<anonymous> (/home/shlomif/e.js:7173:3)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
```

Please look into fixing it.

Regards,

-- Shlomi Fish

**Comment by fglock** [comment]
this works now:

$ node perlito5.js -I src5/lib -e ' my $f; open $f, "<", "perlito5.pl"; print <$f> '
# Do not edit this file - Generated by Perlito5 9.0
...

**Comment by shlomif** [comment]
Thanks for fixing it!
